name: CI

on:
  push:
    branches:
      - "*" # Run on all branches, including main
  pull_request:
    branches:
      - main # Run when a PR targets the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 20.9.0
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0" # Use Node.js 20.9.0

      - name: Install Dependencies with Yarn
        run: yarn install # Install project dependencies using Yarn

      - name: Run Tests with Coverage
        run: yarn test --coverage # Run tests and generate coverage report

      - name: Upload Coverage to Coveralls (only on main)
        if: github.ref == 'refs/heads/main' # Only run if branch is main
        run: npx coveralls < coverage/lcov.info # Upload coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }} # Use the secret token from Coveralls
